### PR TITLE
Add git minimum version requirement

### PR DESCRIPTION
**Pull request by upsj**
We are using `rev-parse --git-path hooks`, which on some RHEL setups and ancient git versions is broken. So let's make that failure more loud.

The version requirement is a rough approximation of when it should have started to work, based on git blame archeology, see https://github.com/git/git/commit/0701530c2663f82ff4b678de27db4c61f8b3092f

Issue found by @fritzgoebel

### CODE REVIEW

**Review by yhmtsai — APPROVED** [review]

**Comment by yhmtsai** [comment]
could you also add it into README?

**Review by thoasm — APPROVED** [review]
LGTM!

**Comment by upsj** [comment]
Fritz confirmed it works :)

**Review by fritzgoebel — APPROVED** [review]
LGTM

**Pull request merged**
